[pytest]
markers = 
    smoke: mark a test as smoke test
    regression: mark a test as regression test
    service : service test
    integration : mark a test as integration test
    auth : mark a test as auth test
    repo : mark a test as repo test
    register : mark a test as register test


pythonpath = .
testpaths = tests
; these two line is very necessary to run the tests without any import error. It tells pytest to look for tests in the "tests" directory and to include the current directory in the Python path, allowing it to find the application code.
